spring.application.name=relaytiming

spring.datasource.url=jdbc:postgresql://localhost:5432/relaytiming
spring.datasource.username=stevensonyan
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

mqtt.enabled=true
mqtt.broker-url=tcp://192.168.1.204:1883
mqtt.client-id=JavaR700Consumer
mqtt.topic=r700/reads
mqtt.qos=1
