spring.application.name=relaytiming

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/relaytiming}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:stevensonyan}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect