spring.application.name=relaytiming

spring.datasource.url=jdbc:postgresql://localhost:5432/relaytiming
spring.datasource.username=stevensonyan
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect